DATN_QLKS/Areas/Admin/Controllers/NhanVienController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DATN_QLKS.Models;

namespace DATN_QLKS.Areas.Admin.Controllers
{
    public class NhanVienController : Controller
    {
        private dataQLKSEntities db = new dataQLKSEntities();
        // GET: NhanVien
        public ActionResult Index()
        {
            var tblNhanViens = db.tblNhanViens.Include(t => t.tblChucVu);
            return View(tblNhanViens.ToList());
        }

        // GET: NhanVien/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblNhanVien tblNhanVien = db.tblNhanViens.Find(id);
            if (tblNhanVien == null)
            {
                return HttpNotFound();
            }
            return View(tblNhanVien);
        }

        // GET: NhanVien/Create
        public ActionResult Create()
        {
            ViewBag.ma_chuc_vu = new SelectList(db.tblChucVus, "ma_chuc_vu", "chuc_vu");
            return View();
        }

        // POST: NhanVien/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ma_nv,ho_ten,ngay_sinh,dia_chi,sdt,tai_khoan,mat_khau,ma_chuc_vu")] tblNhanVien tblNhanVien)
        {
            if (ModelState.IsValid)
            {
                db.tblNhanViens.Add(tblNhanVien);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ma_chuc_vu = new SelectList(db.tblChucVus, "ma_chuc_vu", "chuc_vu", tblNhanVien.ma_chuc_vu);
            return View(tblNhanVien);
        }

        // GET: NhanVien/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblNhanVien tblNhanVien = db.tblNhanViens.Find(id);
            if (tblNhanVien == null)
            {
                return HttpNotFound();
            }
            ViewBag.ma_chuc_vu = new SelectList(db.tblChucVus, "ma_chuc_vu", "chuc_vu", tblNhanVien.ma_chuc_vu);
            return View(tblNhanVien);
        }

        // POST: NhanVien/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ma_nv,ho_ten,ngay_sinh,dia_chi,sdt,tai_khoan,mat_khau,ma_chuc_vu")] tblNhanVien tblNhanVien)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblNhanVien).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ma_chuc_vu = new SelectList(db.tblChucVus, "ma_chuc_vu", "chuc_vu", tblNhanVien.ma_chuc_vu);
            return View(tblNhanVien);
        }

        // GET: NhanVien/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblNhanVien tblNhanVien = db.tblNhanViens.Find(id);
            if (tblNhanVien == null)
            {
                return HttpNotFound();
            }
            return View(tblNhanVien);
        }

        // POST: NhanVien/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                tblNhanVien tblNhanVien = db.tblNhanViens.Find(id);
                db.tblNhanViens.Remove(tblNhanVien);
                db.SaveChanges();
            }
            catch
            {

            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DATN_QLKS/Areas/Admin/Views/NhanVien/Create.cshtml
@model DATN_QLKS.Models.tblNhanVien

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>tblNhanVien</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ho_ten, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ho_ten, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ho_ten, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ngay_sinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngay_sinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ngay_sinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dia_chi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dia_chi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dia_chi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sdt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sdt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sdt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tai_khoan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tai_khoan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tai_khoan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mat_khau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mat_khau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mat_khau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ma_chuc_vu, "ma_chuc_vu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ma_chuc_vu", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ma_chuc_vu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DATN_QLKS/Areas/Admin/Views/NhanVien/Delete.cshtml
@model DATN_QLKS.Models.tblNhanVien

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblNhanVien</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ho_ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ho_ten)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ngay_sinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngay_sinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dia_chi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dia_chi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sdt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sdt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tai_khoan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tai_khoan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mat_khau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mat_khau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblChucVu.chuc_vu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblChucVu.chuc_vu)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DATN_QLKS/Areas/Admin/Views/NhanVien/Details.cshtml
@model DATN_QLKS.Models.tblNhanVien

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>tblNhanVien</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ho_ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ho_ten)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ngay_sinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngay_sinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dia_chi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dia_chi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sdt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sdt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tai_khoan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tai_khoan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mat_khau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mat_khau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblChucVu.chuc_vu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblChucVu.chuc_vu)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ma_nv }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DATN_QLKS/Areas/Admin/Views/NhanVien/Edit.cshtml
@model DATN_QLKS.Models.tblNhanVien

@{
    ViewBag.Title = "Sửa thông tin nhân viên";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Admin</a>
    </li>
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","LoaiPhong")">Nhân Viên</a>
    </li>
    <li class="breadcrumb-item active">Sửa thông tin nhân viên</li>
</ol>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ma_nv)

        <div class="form-group">
            @Html.Label("Họ tên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ho_ten, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ho_ten, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Ngày sinh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngay_sinh, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                @Html.ValidationMessageFor(model => model.ngay_sinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Địa chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dia_chi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dia_chi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("SĐT", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sdt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sdt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Tài khoản", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tai_khoan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tai_khoan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Mật khẩu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mat_khau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mat_khau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Chức vụ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ma_chuc_vu", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ma_chuc_vu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DATN_QLKS/Areas/Admin/Views/NhanVien/Index.cshtml
@model IEnumerable<DATN_QLKS.Models.tblNhanVien>

@{
    ViewBag.Title = "Danh sách nhân viên";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        @Html.ActionLink("Admin", "Index")
    </li>
    <li class="breadcrumb-item active">Danh sách nhân viên</li>
</ol>
<p>
    @Html.ActionLink("Thêm nhân viên", "Create")
</p>
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Danh sách nhân viên
    </div>
    <div class="card-body">
        <div class="table-responsive">

            <table class="table table-bordered table-striped table-hover" id="dataTable" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            Họ tên
                        </th>
                        <th>
                            Ngày sinh
                        </th>
                        <th>
                            Địa chỉ
                        </th>
                        <th>
                            SĐT
                        </th>
                        <th>
                            Tài khoản
                        </th>
                        <th>
                            Chức vụ
                        </th>
                        @if (Session["NV"] != null && ((DATN_QLKS.Models.tblNhanVien)Session["NV"]).ma_chuc_vu <= 2)
                        {
                            <th></th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ho_ten)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ngay_sinh)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.dia_chi)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.sdt)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.tai_khoan)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.tblChucVu.chuc_vu)
                            </td>
                            @if (Session["NV"] != null && ((DATN_QLKS.Models.tblNhanVien)Session["NV"]).ma_chuc_vu <= 2)
                            {
                                <td>
                                    <a href="@Url.Action("Edit","NhanVien",new { id = item.ma_nv})"><div class="btn btn-danger badge-g">Edit</div></a>
                                    <a href="@Url.Action("Details","NhanVien",new { id = item.ma_nv})"><div class="btn btn-info badge-g">Details</div></a>
                                    <a href="@Url.Action("Delete","NhanVien",new { id = item.ma_nv})"><div class="btn btn-secondary badge-g">Delete</div></a>
                                    @*@Html.ActionLink("Edit", "Edit", new { id = item.ma_nv }) |
                                    @Html.ActionLink("Details", "Details", new { id = item.ma_nv }) |
                                    @Html.ActionLink("Delete", "Delete", new { id = item.ma_nv })*@
                                </td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at @DateTime.Now</div>
</div>