DATN_QLKS/Areas/Admin/Controllers/TinNhanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DATN_QLKS.Models;

namespace DATN_QLKS.Areas.Admin.Controllers
{
    public class TinNhanController : Controller
    {
        private dataQLKSEntities db = new dataQLKSEntities();
        // GET: Admin/TinNhan
        public ActionResult Index()
        {
            return View(db.tblTinNhans.ToList());
        }

        // GET: TinNhan/Details
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblTinNhan tblTinNhan = db.tblTinNhans.Find(long.Parse(id));
            if (tblTinNhan == null)
            {
                return HttpNotFound();
            }
            return View(tblTinNhan);
        }
    }
}

DATN_QLKS/Areas/Admin/Views/TinNhan/Details.cshtml
@model DATN_QLKS.Models.tblTinNhan

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Admin</a>
    </li>
    <li class="breadcrumb-item active">Chi tiết tin nhắn</li>
</ol>

<div>
    <dl class="dl-horizontal">
        <dt>
            Ngày gửi
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngay_gui)
        </dd>

        <dt>
            Mã khách hàng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ma_kh)
        </dd>

        <dt>
            Họ tên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ho_ten)
        </dd>

        <dt>
            Mail
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mail)
        </dd>

        <dt>
            Nội dung
        </dt>

        <dd>
            @Html.DisplayFor(model => model.noi_dung)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

DATN_QLKS/Areas/Admin/Views/TinNhan/Index.cshtml
@model IEnumerable<DATN_QLKS.Models.tblTinNhan>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Admin</a>
    </li>
    <li class="breadcrumb-item active">Danh sách tin nhắn</li>
</ol>

<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Danh sách tin nhắn
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover" id="dataTable" cellspacing="0">
                <tr>
                    <th>
                        @Html.DisplayName("Ngày gửi")
                    </th>
                    <th>
                        @Html.DisplayName("Họ tên")
                    </th>
                    <th>
                        @Html.DisplayName("Mail")
                    </th>
                    <th>
                        @Html.DisplayName("Nội dung")
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ngay_gui)
                        </td>
                        <td>

                            @if (item.ma_kh == null)
                            {
                                @item.ho_ten
                            }
                            else
                            {
                                @Html.DisplayFor(modelItem => item.ma_kh)
                            }

                        </td>
                        <td>                           
                                @if (item.ma_kh == null)
                                {
                                    @item.mail
                                }
                                else
                                {
                                    @Html.DisplayFor(modelItem => item.mail)
                                }

                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.noi_dung)
                        </td>
                        <td>
                            <a href="@Url.Action("Details","TinNhan",new { id = item.id})"><div class="btn btn-info badge-g">Details</div></a>
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at @DateTime.Now</div>
</div>